{
  allContacts {
    edges {
      node {
        mail
        facebook
        pl {
          title
          location
          join
        }
        en {
          title
          location
          join
        }
      }
    }
  }
}
